name: Remote ssh command
# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST_DNS }}
          username: ${{ env.USERNAME }}
          key: ${{ env.EC2_SSH_KEY }}
          script: |
            cd /var/www/html/github/github-pipeline
            git pull

